<?php

namespace AppBundle\Repository;

/**
 * DrenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrenRepository extends \Doctrine\ORM\EntityRepository
{
}
